- name: Get Paswd from Vault
  hosts: localhost
  connection: local
  tasks:
    - name: get passwd
      ansible.builtin.debug:
        msg: "{{ lookup('hashi_vault', 'test/data/credentials:Password token={{ vault_token }} url=https://54.166.78.232:8200 validate_certs=False')}}"